{% set version = "0.0.18" %}

package:
  name: mobility_mapper
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4f/c0/221c7c48cf166713a38826e21a3faefe27a9f111417c44e0e1774a75b26d/mobility-mapper-0.0.17.tar.gz
  sha256: 713906ceaf7074408ccce961f4944056030eb813fb0fde09491b40bc265c332d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - opencv
    - pyqt
    - pyqtgraph

test:
  imports:
    - mobilitymapper

about:
  home: https://github.com/researchgrant/mobility-mapper
  license: MIT
  summary: 'Track mobility bouts over time'
  description: |
    This app allows allows for the scoring of behavioral videos involving mobility (or any other binary behavior).
  dev_url: https://github.com/researchgrant/mobility-mapper
  doc_url: https://pypi.org/project/mobility-mapper/
  doc_source_url: https://github.com/researchgrant/mobility-mapper/blob/master/README.md