{% set version = "0.0.17" %}

package:
  name: mobility_mapper
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/mobility-mapper/mobility-mapper-{{ version }}.tar.gz
  sha256: f3832918bc3c66617f92e35f5d70729187676313caa60c187eb0f28b8fe5e3b5

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mobilitymapper

about:
  home: https://github.com/researchgrant/mobility-mapper
  license: MIT
  summary: 'Track mobility bouts over time'
  description: |
    This app allows allows for the scoring of behavioral videos involving mobility (or any other binary behavior).
  dev_url: https://github.com/researchgrant/mobility-mapper
  doc_url: https://pypi.org/project/mobility-mapper/
  doc_source_url: https://github.com/researchgrant/mobility-mapper/blob/master/README.md